# Generated by Django 4.2 on 2023-05-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriconsult', '0002_consult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consult',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='consult',
            old_name='nutritionist_id',
            new_name='nutritionist',
        ),
    ]
