# Generated by Django 4.2 on 2023-05-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriconsult', '0003_rename_client_id_consult_client_and_more'),
    ]

    operations = [
    ]
