# Generated by Django 4.2 on 2023-05-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriconsult', '0004_auto_20230508_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='consult_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
